apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitest
  labels:
    app: apitest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apitest
  template:
    metadata:
      labels:
        app: apitest
    spec:
      containers:
        - name: apitest
          image: apiacre.azurecr.io/apitest:v1  # Update with your ACR image
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "apitesting.postgres.database.azure.com"
            - name: DB_USER
              value: "admin2"
            - name: DB_PASSWORD
              value: "Password@123"
            - name: DB_NAME
              value: "postgres"
